version: '3.4'
services:
  server:
    image: ghcr.io/aliparlakci/country-roads/server:latest
    restart: always
    env_file: .env

  pwa:
    image: ghcr.io/aliparlakci/country-roads/pwa:latest
    restart: always

  redis:
    image: "redis:alpine"
    restart: always
    env_file: .env
    ports:
      - "6379:6379"

  proxy:
    build: 
      context: proxy
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - server
      - pwa