// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aliparlakci/country-roads/validators (interfaces: Validator,IValidatorFactory)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	validators "github.com/aliparlakci/country-roads/validators"
	gomock "github.com/golang/mock/gomock"
)

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// SetDto mocks base method.
func (m *MockValidator) SetDto(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDto", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDto indicates an expected call of SetDto.
func (mr *MockValidatorMockRecorder) SetDto(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDto", reflect.TypeOf((*MockValidator)(nil).SetDto), arg0)
}

// Validate mocks base method.
func (m *MockValidator) Validate(arg0 context.Context) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockValidatorMockRecorder) Validate(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockValidator)(nil).Validate), arg0)
}

// MockIValidatorFactory is a mock of IValidatorFactory interface.
type MockIValidatorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIValidatorFactoryMockRecorder
}

// MockIValidatorFactoryMockRecorder is the mock recorder for MockIValidatorFactory.
type MockIValidatorFactoryMockRecorder struct {
	mock *MockIValidatorFactory
}

// NewMockIValidatorFactory creates a new mock instance.
func NewMockIValidatorFactory(ctrl *gomock.Controller) *MockIValidatorFactory {
	mock := &MockIValidatorFactory{ctrl: ctrl}
	mock.recorder = &MockIValidatorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIValidatorFactory) EXPECT() *MockIValidatorFactoryMockRecorder {
	return m.recorder
}

// GetValidator mocks base method.
func (m *MockIValidatorFactory) GetValidator(arg0 string) (validators.Validator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidator", arg0)
	ret0, _ := ret[0].(validators.Validator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidator indicates an expected call of GetValidator.
func (mr *MockIValidatorFactoryMockRecorder) GetValidator(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidator", reflect.TypeOf((*MockIValidatorFactory)(nil).GetValidator), arg0)
}
