# This is a basic workflow to help you get started with Actions

name: Docker

on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag name
        id: tag_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Publish server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/aliparlakci/country-roads/server:latest
            ghcr.io/aliparlakci/country-roads/server:${{ steps.tag_name.outputs.SOURCE_TAG }}
      - name: Publish pwa
        uses: docker/build-push-action@v2
        with:
          context: ./pwa
          push: true
          tags: |
            ghcr.io/aliparlakci/country-roads/pwa:latest
            ghcr.io/aliparlakci/country-roads/pwa:${{ steps.tag_name.outputs.SOURCE_TAG }}
